### ISSUE TITLE
Code 

### ISSUE THREAD

**Issue by NikitaKononov** [ShunyuYao/DFA-NeRF#1]
Hello)
How soon do you plan to release the code? Looking forward for it, thanks for your work

**Comment by NikitaKononov** [comment]
Hello?)

**Comment by yaleimeng** [comment]
又一个僵尸项目。以后对于没开源的就不细看论文了

**Comment by aishoot** [comment]
Nice work! +1 request

**Comment by Perseus1993** [comment]
想看code

**Comment by silence-tang** [comment]
When will the code be released, looking forward for it!!! qwq qwq

**Comment by soonwonh** [comment]
If the code's are not released at all, we should regard the paper's correctness to be not grounded well. I don't think this paper works as authors claimed.

**Comment by ShunyuYao** [comment]
The code has been released. Greatly sorry for the very late time to release the codes.
